### ISSUE TITLE
Twingate uninstaller script

### ISSUE THREAD

**Issue by NateGre** [Twingate-Solutions/general-scripts#14]
on line 32

Get-WmiObject -Class Win32_Product | Where-Object{$_.Name.Contains("Twingate")}

IdentifyingNumber : {11BA3B45-D8FA-4524-A085-80FB4B0AB424}
Name              : Twingate 2024.235.2199
Vendor            : Twingate Inc.
Version           : 20.24.235.2199
Caption           : Twingate 2024.235.2199

You cannot call a method on a null-valued expression.
At line:1 char:51
+ ... ect -Class Win32_Product | Where-Object{$_.Name.Contains("Twingate")}
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

potential fix:

Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -and $_.Name.Contains("Twingate")}

**Comment by bcameron-twingate** [comment]
That's really interesting, the same section of code exists in the installer script as well (in case you want to do a clean install) and I've never seen that error with or without the client app already installed.  If it doesn't find it then it just doesn't seem to care.

What version of Powershell are you running it in, 5.x or 7.x?  Is this Win10/11 or server?  Anything special about the machine?
